### ISSUE TITLE
Title text not rendering in Canary.

### ISSUE THREAD

**Issue by danielmatthew** [alexlande/alexlande.github.com#2]
Hi Alex,

Just a heads up:

![screen shot 2016-06-11 at 19 50 23](https://cloud.githubusercontent.com/assets/111794/15986913/f67b35d8-300d-11e6-988e-f7c19538d16c.png)

This was in Canary 53.0.2761.2 (64-bit), but it renders A-OK in Chrome 50.0.2661.102 (64-bit), Safari and Firefox.

Wondered if there's a bug with the `mix-blend-mode` properties. If I set it to `screen` I see the gradient applied to the text, rather than the block, but it's incredibly pale (as you'd expect on a white background).

Keep up the good work 👍

**Comment by danielmatthew** [comment]
...and looks as though it was a bug, fixed in `53.0.2766.0`

🎉

**Comment by alexlande** [comment]
The best kind of bug 😄 . Thanks @danielmatthew!
